{% set version = "0.8.1" %}

package:
  name: sphinx-gallery
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-gallery/sphinx-gallery-{{ version }}.tar.gz
  sha256: 92b7ae7850f770c3f605cfbadc116f1177771f6eb50e22052e4226ebba9f3449

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3
    - pip
    - pytest-runner
  run:
    - python >=3
    - matplotlib-base
    - pillow
    - sphinx >=1.8.3

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - sphinx_gallery
    - sphinx_gallery.gen_gallery

about:
  home: https://github.com/sphinx-gallery/sphinx-gallery
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx extension for automatic generation of an example gallery
  description: |
    A Sphinx extension that builds an HTML gallery of examples from any set of
    Python scripts. It is extracted from the scikit-learn project and aims to
    be an independent general purpose extension.
  doc_url: https://sphinx-gallery.github.io
  dev_url: https://github.com/sphinx-gallery/sphinx-gallery

extra:
  recipe-maintainers:
    - dfroger
    - leouieda
    - ocefpaf
