travis:
  secure:
    BINSTAR_TOKEN: UDbeR3B8fvLawsXEoRf1GVW6zIdGLULK1ofXgYB4OzgkGsjNaKlRRdhkfE2ugldG91n/jBYr71IK/noe/7Ie64Nln0a8YvF7Px4mLl4XVGTq5OB0lJuUfulg9PywZOPyh0iw8FVK4Lt1+v5n0LR0h14K8JwPtP0rofrYLZQpznQUXzBGjm9Ff3bz2RQgKvt5t1Vtdh0D8R6C53VUK8xkkGRN9mpFjdgg+xwl8LrRnpgPcGO4Op5V23fptFNKWhHdXgrJt3QHguShAtMvDiXolQXweUcxp91EP0WIhxDvH6/5c/B3axAz3WV0Xc1xauepTxRMNRm5rnGMCowvjqTFMwoB7ZOjMLwoHxCOzi6baNvn9GItsFTZ8JwfdS03URhsJFkMO9LzxEVKDiEWVIHl4dpEN+7JlC5ebz8sUabQ1kPbZgJuhTNrOFcvO1bBijVZYPajmb0EjHlyfKYC+G90qapFodIeMEAdVNzqI592FruQ8PklNM/Twk0z/R4hpQc0X1g+am5kMwXFrwyxzSFUKru8Zz7aAc04jHi7m22j7UXLYyfPcDdNHJn54p6hS5hrTPAzTcRd8lIQ4CxbRkYjyWQdVk7O5YaAdZVFO7JaKcB2AUqOcm6haKyg4t9HfRpRUDlhC1LKwaxpA3ZF713nGBtbfy+bBtndmeKD23dEAUM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
