travis:
  secure:
    BINSTAR_TOKEN: TjbliywOOLQZHBXg85FHnrsHr65DtXYwYEDqruuyn4WU3I/M7MIB2z3jbIMi0a49hA9O/di+7GRmC8m8ZWksHWz25VKidKw6aTrocaCvZdIUbvX+f71R5TuFvxNfigKMgAa24c33MJGsl6/0LOyskYBaevYvyaiBqKpYkuRfQ142nZo2zT9LdOqFkOMZTGGyQklOBl9ywCJAb7KPHdji1FWZcxxiJrsMdxJYYfJYvVwqRNmbAdKbmP9Uetvs7haN0GE7nMKC0oDgclZWnoGTEwB4wIIAnLS+8p1bUeEg6pLy5Dy6EI3oCPBEc+SJk42WdTVvZdvcCH8l5Pdfp6KD30u401+bdYNUi4F5+EQNG+ajKMCYoYIv6A4PAn4/Daf7PmdZwRHCXeAzx00JbdYa+AhtzbZRHyxq4OoXlb1C6Tu3fZ8VGV3Mwx4CYVBr84ZFw9+Ri/z5P0UbHJ+e91YgA3VxfngRj8t7YWQxKbjqnJ1qnf5Ys7OcvE99LTeBq5omq1xGKNZsCZI8cYnSR+SJZLMh0JTElxmroV/w/lhu4JLf4sWkGTE2F70LSz2CWdkLn0p+A8wbPZ3tm9ASbFRJA8Vuh8e+YrPIi38zh4lw1EGmEXIROdrDh3eREo2Ukij9rIDyuKR/6g4WG4C1oLDwSlv4tV8EoSY0q4LES11ZpM4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
