appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UBp6taHGU0JVFAq8gpXHYPCT4pwc/7Yse07nRn1gyWjJ7hb5pkow4B3nPyvM9xyQmWjiZBZDa898TGTVYFxR8Rotp+zgojIMYsUt/qRZS2V6xSm50yUF6SB143IKNE9f8AQNZ4UDUNl8Ii6GwumFjavfoviTJrOzP9Z/gwwT+TEuQdqzVf5ACm0ujM3G772Q6DvoMg7+bapwQxjaRUXoajm6ljy4hgUD7ltQ/NtOKiA7m9gMO3GJKkxL5du2JNplEnHgAChw581LGrBWDarnjIRrkS7NAhYVkMOIBOhcoYAc2EXnVlzo89Kfl3t2/ScPep+qDuBNCe47UcgtzmywZBrAaqZ1NMhSx/a3xwe7yVg3nGYnSDe8l3Qbndt6b5Ty7GkubNgdTyNgrdqkEOm9kdbkI5EjC+7etWKv64VUBv3eYlBIBG5eMCYmIpbHdhW+plPrGJRu1u886NDZDsT4KMpbLtmZeI7NNXVm9nFl61Ei0ppKhdE8rktMxLum988MPbANOaZ91jtVcmL+uORB9vSW6IELp221SWW6OYiyE91T1AxQxjmMy77bY+Qno762lF59l8dpI9/CFzx0J8lme86rWxLC5Pzr0G2KrHPlyNoYxgAkamLjQDr8RvLsOX8k5zeKtiSZ7x0Rak4vRvmdOkiGmqHf0vGEz4Wt7WVKh0s=}
provider:
  win: azure
